namespace Rimaethon.Scripts.Core.Enums
{
    public enum GameEvents
    {
        OnPlayingAudio,
        OnSceneChange,
        OnPageChange,
        OnUIBack,
        OnHealthChange,
        OnPlayerJump,
        OnPlayerGravityChange,
        OnPlayerFalling,
        OnPlayerMovement,
        OnPlayerDamaged,
        OnGemCollected,
        OnPlayerDead,
        OnPause,
        OnResume,
        OnLevelEnter,
        OnLevelExit,
        OnPlayerRespawn,
        OnPlayerRespawned,
        OnEnemyDead,
        OnScreenshot,
        OnGameStart,
        OnPlayerDirectionChange,
        OnPlayerInSight,
        OnPlayerMelted,
        OnRedGemCollected
    }
}